import "./style/globals.scss";
import { DM_Sans } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
export const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={dmSans.className}>{children}</body>
    </html>
  );
}
